---
title: THS-1_hold
author: Himawork
date: '2020-06-29'
slug: THS-1_2020-06-29_hold
categories:
  - HTML
tags:
  - Reports
  - Trade
  - hold
---

```{r Load_Functions, echo=FALSE, warning=FALSE}
# load packages and functions ----
suppressMessages({library(rvest); library(recharts)})
# sword to test stock value moving direction
bandSword <- function(Scode, type = 'sting', days = 10, ratio = 0.8, bandFrom = 30) {
  datK.old = readRDS('e:/tess/SpySto.RDS')[[type]][[Scode]][['dailyK']]
    if (length(datK.old$Date) < bandFrom) {
    print('bandFrom out of datK boundary, use default length of datK.')
    bandFrom = length(datK.old$Date)
  }
  datK.old$sword = NA; bandRes = NULL
  for (i in 1:length(datK.old$Date)) {
    datK.old$sword[i] = (datK.old$OPEN[i] > datK.old$CLOSE[i] | datK.old$OPEN[i] <  datK.old$CLOSE[i + 1])
    # defination
    # OPEN > CLOSE & OPEN < CLOSE[1]: + 2; OPEN > CLOSE & OPEN > CLOSE[1]: + 1
    # OPEN < CLOSE & OPEN < CLOSE[1]: + 1; OPEN < CLOSE & OPEN > CLOSE[1]: + 0
  }
  # 
  for (b in bandFrom:1) {
      NumCro = length(grep('TRUE',datK.old$sword[b:(b + days)])) >= ceiling(days * ratio) 
      bandDate = datK.old$Date[b];
    if (NumCro) {
      bandTest = TRUE
      Hvalue = datK.old$HIGH[which(datK.old[,'Date'] == bandDate)]
      if (length(Hvalue) != 1) {Hvalue = max(datK.old$LOW[b:(b + days)])}
      banddat = data.frame(Date = bandDate, Test = bandTest, NumCro = NumCro, High = Hvalue * 1.01)
      bandRes = rbind.data.frame(bandRes, banddat)
    } 
  }
  return(bandRes)
}
# calculate profit
bandProfit <- function(Scode, bandRes = '', MaxTestDays = 5, MaxHoldDays = 30, Proless = 200) {
  if (length(bandRes) < 1) { 
    print(paste0('No profit band of stock ',Scode))
  } else {
    datK.old = na.omit(readRDS('e:/tess/SpySto.RDS')[['sting']][[Scode]][['dailyK']])
    bandRes$Date = as.character(bandRes$Date); profit = 0; 
    Buydat = NULL;  BS.datT = NULL; 
    BS.dat = data.frame(bandDate = 'd', BS.Date = 'BuyDate', buyN = 0, sellN = 0, price = 0, 
                        FinalHold = 0, money = 0, profit = '.', Hday ='.', Pro.day = '.', tags = 'new')
    for (d in bandRes$Date) {
      FinalHold = 0; HoldStoNum = 0; money = 50000; 
      for (m in 1:MaxTestDays) {
        Sday = which(datK.old$Date==d) - m
        Sday <- ifelse(length(Sday) ==1,Sday,0)
        ## test buy env and buying new stocks
        if (Sday > 1) {
          Sdat = datK.old[c(Sday),]; Sdat$Date = as.character(Sdat$Date) 
          # Sdat = datK.old[c(Sday,Sday+1),] # this Sdat get big profit
          PriHigh = max(Sdat$HIGH) *.9 + min(Sdat$LOW) *.1; PriLow = max(Sdat$HIGH) *.1 + min(Sdat$LOW) *.9
          Close = datK.old[Sday+1,'CLOSE']; MA10 = mean(colMeans(datK.old[1:10,c('CLOSE','OPEN')]))
          # set buy condition
          ChangeRateH = (PriHigh - Close)/Close * 100; ChangeRateL = (PriLow - Close)/Close * 100
          sdJ1 = datK.old[Sday+1,'J'] - datK.old[Sday+2,'J'];sdJ2 = datK.old[Sday+2,'J'] - datK.old[Sday+3,'J']
          sdJ1 = ifelse(!anyNA(sdJ1),sdJ1,0); sdJ2 = ifelse(!anyNA(sdJ2),sdJ2,0); 
          meanVib = mean(na.omit(readRDS('e:/tess/SpySto.RDS')[['sting']][[Scode]][['CStoDetail']][1:5,8]))
          meanVib = ifelse(anyNA(meanVib), 2, meanVib)
          VibCR = ((ChangeRateH - ChangeRateL) > meanVib/2)
          # test buy in new stocks
          if (sdJ1 > sdJ2 & FinalHold == 0 & Sdat$J < 90 & Close <= MA10 & VibCR) { # & dayPriT 
            # cat(paste0('bandWeek: ',d,'| Got true buy env of ', Scode,'\n\tBuyDay: ',Sdat$Date[1],'\n'))
            if (ChangeRateL <= -8) {
              # cat('\tBuying: ChangeRate <= -7 and AddholdNum = 1000\n')
              HoldStoNum = 1000
              money = money - PriLow * HoldStoNum
            } else if (ChangeRateL <= -5 & ChangeRateL > -8) {
              # cat('\tBuying: -3 <= ChangeRate < -7 and AddholdNum = 500\n')
              HoldStoNum = 700
              money = money - PriLow * HoldStoNum
            } else if (ChangeRateL <= -2 & ChangeRateL > -5) {
              # cat('\tBuying: -1 <= ChangeRate < -3 and AddholdNum = 200\n')
              HoldStoNum = 600
              money = money - PriLow * HoldStoNum
            } else if (ChangeRateL <= 1 & ChangeRateL > -2) {
              # cat('\tBuying: -1 <= ChangeRate < -3 and AddholdNum = 200\n')
              HoldStoNum = 500 
              money = money - PriLow * HoldStoNum
            }
            FinalHold = FinalHold + HoldStoNum
          }
          if (FinalHold > 0 & !Sdat$Date %in% BS.dat$bandDate) {
            BuyDate = Sdat$Date; Hvalue1 = Sdat$HIGH * 1.01; Lvalue1 = Sdat$LOW
            BS.dat = data.frame(bandDate = d, BS.Date = BuyDate, buyN = FinalHold, sellN = 0, price = PriLow, 
                                FinalHold = FinalHold, money = money, profit = 0, 
                                Hday = '.', Pro.day = '.', tags = 'new')
            break()
          } else {
            FinalHold = 0; money = 50000
            break()
          }
        }
      }
      # test buy or sell after buying new stocks
      for (b in 1:MaxHoldDays) {
        ## set and test buy/sell condition in second day
        Hday = Sday - b
        if (Hday > 0 & FinalHold != 0) {
          Hdat = datK.old[c(Hday),]; Hdat$Date = as.character(Hdat$Date) 
          PriHigh = max(Hdat$HIGH) *.9 + min(Hdat$LOW) *.1; PriLow = max(Hdat$HIGH) *.1 + min(Hdat$LOW) *.9
          Close = datK.old[Hday+1,'CLOSE']; 
          # set buy condition
          ChangeRateH = (PriHigh - Close)/Close * 100; ChangeRateL = (PriLow - Close)/Close * 100
          sdJ1 = datK.old[Hday+1,'J'] - datK.old[Hday+2,'J'];sdJ2 = datK.old[Hday+2,'J'] - datK.old[Hday+3,'J']
          sdJ1 = ifelse(!anyNA(sdJ1),sdJ1,0); sdJ2 = ifelse(!anyNA(sdJ2),sdJ2,0); 
          # sword trade 
          # swordTest = Sword(Scode, days = 7, ratio = 0.7) == 'UP'
          # if (swordTest) {
          #   # cat('\t|GoSell.1000 on day',Hdat$Date[1],'\n')
          #   minusCount = ifelse(FinalHold > 1000, 1000, FinalHold - 100)
          #   FinalHold = FinalHold - minusCount
          #   money = money + PriHigh * minusCount
          #   BS.dat.i = data.frame(bandDate = '.', BS.Date = Hdat$Date[1], buyN = 0, sellN = minusCount,  price = PriHigh, 
          #                         FinalHold = FinalHold, money = money, profit='.',
          #                         Hday ='.', Pro.day = '.', tags = 'minus')
          #   BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
          # }
          # test PriHigh and PriLow 
          if (sdJ1 > sdJ2) {
            # test to abort with limit profit before buy new
            if (money + FinalHold * PriHigh - 50000 > Proless) {
              # cat('\t|GoSell.all on day',Hdat$Date[1],'\n')
              money = money + PriHigh * FinalHold; gain = round(money - 50000,2)
              Hdays = as.numeric(as.Date(Hdat$Date[1]) - as.Date(BS.dat$BS.Date[1]))
              BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 0, sellN = FinalHold,  price = PriHigh, 
                                    FinalHold = 0, money = money, profit = gain, 
                                    Hday = Hdays, Pro.day = round(gain / Hdays, 2), tags = 'Pro.cls')
              BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
              FinalHold = 0; break()
            }
            # test buy
            # cat(paste0('\t|testBuyorSell...on day: ',Hdat$Date[1],'\n'))
            if (ChangeRateL <= -8 & FinalHold != 0  & Hday > 1) {
              # cat('\t|GoBuy.1000 on day',Hdat$Date[1],'\n')
              FinalHold = FinalHold + 1000
              money = money - PriLow * 1000; gain = round(money + FinalHold * PriHigh - 50000,2)
              BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 1000, sellN = 0,  price = PriLow, 
                                    FinalHold = FinalHold, money = money, profit = gain, 
                                    Hday = '.', Pro.day = '.', tags = 'plus')
              BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
            } else if (ChangeRateL > -8 & ChangeRateL <= -6 & FinalHold != 0  & Hday > 1) {
              # cat('\t|GoBuy.700 on day',Hdat$Date[1],'\n')
              FinalHold = FinalHold + 700
              money = money - PriLow * 700; gain = round(money + FinalHold * PriHigh - 50000,2)
              BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 700, sellN = 0,  price = PriLow, 
                                    FinalHold = FinalHold, money = money, profit = gain, 
                                    Hday = '.', Pro.day = '.', tags = 'plus')
              BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
            } else if (ChangeRateL > -6 & ChangeRateL <= -4 & FinalHold != 0  & Hday > 1) {
              # cat('\t|GoBuy.500 on day',Hdat$Date[1],'\n')
              FinalHold = FinalHold + 600
              money = money - PriLow * 600; gain = round(money + FinalHold * PriHigh - 50000,2)
              BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 600, sellN = 0,  price = PriLow, 
                                    FinalHold = FinalHold, money = money, profit = gain, 
                                    Hday = '.', Pro.day = '.', tags = 'plus')
              BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
            } else if (ChangeRateL > -4 & ChangeRateL <= -2 & FinalHold != 0  & Hday > 1) {
              # cat('\t|GoBuy.300 on day',Hdat$Date[1],'\n')
              FinalHold = FinalHold + 500
              money = money - PriLow * 500; gain = round(money + FinalHold * PriHigh - 50000,2)
              BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 500, sellN = 0,  price = PriLow, 
                                    FinalHold = FinalHold, money = money, profit = gain, 
                                    Hday = '.', Pro.day = '.', tags = 'plus')
              BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
            } 
            # test sell
            if ((ChangeRateH >= 1 & ChangeRateH < 3) & FinalHold != 0) { # | dayPriT 
              # cat('\t|GoSell.200 on day',Hdat$Date[1],'\n')
              minusCount = ifelse(FinalHold > 300, 300, 0)
              if (minusCount != 0) {
                FinalHold = FinalHold - minusCount
                money = money + PriHigh * minusCount; gain = round(money + FinalHold * PriHigh - 50000,2)
                BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 0, sellN = minusCount,  price = PriHigh, 
                                      FinalHold = FinalHold, money = money, profit = gain,
                                      Hday ='.', Pro.day = '.', tags = 'minus')
                BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
              }
            } else if (ChangeRateH >= 3 & ChangeRateH < 5 & FinalHold != 0) {
              # cat('\t|GoSell.500 on day',Hdat$Date[1],'\n')
              minusCount = ifelse(FinalHold > 500, 500, FinalHold - 100)
              FinalHold = FinalHold - minusCount
              money = money + PriHigh * minusCount; gain = round(money + FinalHold * PriHigh - 50000,2)
              BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 0, sellN = minusCount,  price = PriHigh, 
                                    FinalHold = FinalHold, money = money, profit = gain,
                                    Hday ='.', Pro.day = '.', tags = 'minus')
              BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
            } else if (ChangeRateH >= 5 & ChangeRateH < 7 & FinalHold != 0) {
              # cat('\t|GoSell.700 on day',Hdat$Date[1],'\n')
              minusCount = ifelse(FinalHold > 700, 700, FinalHold - 100)
              FinalHold = FinalHold - minusCount
              money = money + PriHigh * minusCount; gain = round(money + FinalHold * PriHigh - 50000,2)
              BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 0, sellN = minusCount, price = PriHigh, 
                                    FinalHold = FinalHold, money = money, profit = gain,
                                    Hday ='.', Pro.day = '.', tags = 'minus')
              BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
            } else if (ChangeRateH >= 7 & FinalHold != 0) {
              # cat('\t|GoSell.1000 on day',Hdat$Date[1],'\n')
              minusCount = ifelse(FinalHold > 1000, 1000, FinalHold - 100)
              FinalHold = FinalHold - minusCount
              money = money + PriHigh * minusCount; gain = round(money + FinalHold * PriHigh - 50000,2)
              BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 0, sellN = minusCount,  price = PriHigh, 
                                    FinalHold = FinalHold, money = money, profit = gain,
                                    Hday ='.', Pro.day = '.', tags = 'minus')
              BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
            }
          }
        }
      }
      if (FinalHold > 0) {
        money = money + PriHigh * FinalHold; gain = round(money - 50000,2)
        Hdays = as.numeric(as.Date(Hdat$Date[1]) - as.Date(BS.dat$BS.Date[1]))
        BS.dat.i = data.frame(bandDate = d, BS.Date = Hdat$Date[1], buyN = 0, sellN = FinalHold,  price = PriHigh, 
                              FinalHold = 0, money = money , profit = gain , 
                              Hday = Hdays, Pro.day = round(gain / Hdays, 2), tags = 'End.cls')
        BS.dat = rbind.data.frame(BS.dat, BS.dat.i)
      }
      if (money != 50000) {
        # cat(paste0('\tFinal got money with ',money,' at bandWeek ',d,' on day of ',Hdat$Date[1],'\n\t',paste0(rep('-',73),collapse = ''),'\n'))
        profit = profit + money - 50000
        profit.i = money - 50000
        SellDate = Hdat$Date[1]; Hvalue2 = Hdat$HIGH[1] * 1.02
        Buydat.i <- data.frame(name1 = Lvalue1, xAxis1 = BuyDate, yAxis1 = Hvalue1,
                               name2 = Hvalue2, xAxis2 = SellDate, yAxis2 = Hvalue2,value = profit.i)
        
        Buydat <- rbind.data.frame(Buydat, Buydat.i) # for animation mark lines 
        #
        BS.datT = rbind.data.frame(BS.datT, BS.dat)
      }
    }
    #
    cat(paste0('Finally got ',length(unique(BS.datT$bandDate)),' trading band:'))
    # print(knitr::kable(head(BS.datT)))
    # total profit
    cat(paste0('\nProfit of ',Scode,' was ', round(profit,2),'\n'))
    BS.datT$BS.Date = substr(BS.datT$BS.Date, 6, 10)
    return(list(BS.datT = BS.datT, Buydat = Buydat))
  }
}
# plot K-kines
SpyKplot = function(Scode = '', type = c('sting'), bandRes = bandTest, Protest = ProRes[['Buydat']], 
                    Randtheme = F, viewNum = 60) {
  BuyScodeNum = names(readRDS('e:/tess/SpySto.RDS')[[type]])
  if (Scode %in% BuyScodeNum) {
    dataK = readRDS('e:/tess/SpySto.RDS')[[type]][[Scode]][['dailyK']]
    dataK = na.omit(dataK[duplicated(dataK$Date)==F,])
    if (nrow(dataK) < viewNum) {
      viewNum <- nrow(dataK)
      cat(paste0('ViewNum out of boundary. Use default ',nrow(dataK), ' nrows of dataK.\n'))    }
    # re-order date
    dataK = dataK[1:viewNum,]
    dataK = dataK[order(dataK$Date, decreasing = F),]
    if (Randtheme) {
      theme = c("asis", "default", "macarons", "infographic", "blue", "dark", "gray", "green", "helianthus", 
                "macarons2", "mint", "red", "roma", "sakura", "shine", "vintage")[runif(1,1, 16)]
    } else {theme = 'default'}
    # K line
    Kplot <-  echartr(dataK, as.character(Date), c('OPEN', 'CLOSE', 'LOW', 'HIGH'), type='k') %>%  
      # set_grid(width = 800, height = 300,widget = 'pane') %>%
      setXAxis(name='', axisLabel=list(rotate=45,textStyle=list(fontSize = 8.5))) %>%
      set_theme(width = 1000,height = 360, theme = theme) %>%  set_legend(show = F)%>% 
      setYAxis(name="Price") %>% setToolbox(show = T,controls = c("dataZoom", "restore"), pos = 3)%>% 
      setTitle(subtitle =  paste0('dailyK_plot of ', Scode), pos =12,
               sublink = paste0("http://stockpage.10jqka.com.cn/", Scode)) %>%
      setTooltip(show=T, bgColor = "rgba(0,0,0,0)", textStyle = list(fontSize=8.5, color = 'black')) %>% 
      setDataZoom(fill=rgba(c(col2rgb('lightgreen'), 0.2)), handle=rgba(c(col2rgb('darkgreen'), 0.5)), range = c(50,100))
    # add mark points and lines
    if (dim(bandRes) >= c(1, 1)) {
      names(bandRes) = c('xAxis','value','name','yAxis')
      Kplot <- Kplot %>% addMP(data = bandRes,symbol = 'pin',symbolSize =3,effect = list(show = F,color='green'))
      if (length(Protest) > 0) {
        if (dim(Protest) > c(1, 1)) {
          Buydat = Protest
          for (n in 2:nrow(Buydat)) {
            if (Buydat$xAxis1[n] == Buydat$xAxis1[n-1]) {
              Buydat$yAxis1[n] = Buydat$yAxis1[n-1] * 1.01
              Buydat$value[n] = Buydat$value[n] + Buydat$value[n-1]
              Buydat$value[n-1] = NA
            }
          }
          Kplot <- Kplot %>% addML(data = Buydat, symbolSize = c(1, 1), mode = 'override', 
                                   effect = list(show = T,color = 'blue',loop = TRUE, period = 60, scaleSize = 1))
        }
      }
      return(Kplot)
    }
  } else {print(paste0(Scode,' is not in subdata of ',type))}
}
# plot stock trading details
StoQplot = function(Scode = '', type = c('sting'), plot = c('StoIO', 'StoVP'), viewNum = 60) {
  BuyScodeNum = names(readRDS('e:/tess/SpySto.RDS')[[type]])
  if (Scode %in% BuyScodeNum) {
    Qplot.dat = readRDS('e:/tess/SpySto.RDS')[['sting']][[Scode]][['CStoDetail']]
    if (nrow(Qplot.dat) < viewNum) {
      viewNum <- nrow(Qplot.dat)
      cat(paste0('ViewNum out of boundary. Use default ',nrow(Qplot.dat), ' nrows of Qplot data.\n'))    }
    # re-order date 
    Qplot.dat = Qplot.dat[1:viewNum,]
    Qplot.dat = Qplot.dat[order(Qplot.dat$compTime, decreasing = F),]
    if (plot == "StoIO") {
      # stock in and out
      cat(paste0('Volume In/Out plot of stock ',Scode,"\n"))
      Qplot.dat = na.omit(Qplot.dat[duplicated(Qplot.dat$compTime)==F,c(1,10:15)])
      dat.melt = data.table::melt(Qplot.dat,id ='compTime',measure=c('StoIN.max','StoIN.mid','StoIN.min'))
      dat.melt2 = data.table::melt(Qplot.dat,id ='compTime',measure=c('StoOUT.max','StoOUT.mid','StoOUT.min'))
      dat.melt2$value = -dat.melt2$value # ; dat.melt$class = 'StoIN'; dat.melt2$class = 'StoOUT'
      Qplot = echartr(rbind.data.frame(dat.melt, dat.melt2), as.character(compTime), value, variable, 
                      type='area', subtype = 'stack') %>%
        setTitle(subtitle = "Trading quantity: StoOUT vs. StoIN", pos = 12, 
                 sublink = paste0("http://stockpage.10jqka.com.cn/", Scode)) %>%  
        setXAxis(name = "", axisLabel = list(rotate = 30, textStyle=list(fontSize = 8.5))) %>% setYAxis(name = "万元") %>%  
        setTooltip(show=T, trigger = 'axis', bgColor = "rgba(0,0,0,0)", textStyle = list(fontSize=9, color = 'black')) %>%
        set_theme(width = 1000,height = 360, theme = 'macarons') %>% 
        setToolbox(show = T,controls = c("dataZoom", 'restore'), pos = 3) %>% 
        setDataZoom(fill=rgba(c(col2rgb('lightgreen'), 0.2)), handle=rgba(c(col2rgb('darkgreen'), 0.5)), range = c(50,100))
    } else if (plot == "StoVP") {
      # plot of stock trading change
      cat(paste0('PBR(%) & PER(%) & VR(%) & TR(%) plot of stock ',Scode,"\n"))
      Qplot.dat = Qplot.dat[duplicated(Qplot.dat$compTime)==F,c(1,6:9)]
      BD.dat = rbind.data.frame(data.frame(date = Qplot.dat$compTime, value = Qplot.dat[,2], class = 'PBR/%'),
                                data.frame(date = Qplot.dat$compTime, value = Qplot.dat[,3], class = 'PER/%'),
                                data.frame(date = Qplot.dat$compTime, value = Qplot.dat[,4], class = 'Vib/%'),
                                data.frame(date = Qplot.dat$compTime, value = Qplot.dat[,5], class = 'Tra/%'))
      BD.dat$value = round(BD.dat$value, 2)
      Qplot = echartr(BD.dat, as.character(date),value, class, type='area', subtype = 'smooth') %>% 
        setTitle(subtitle = "PBR(%) & PER(%) & VR(%) & TR(%)", pos = 12,
                 sublink = paste0("http://stockpage.10jqka.com.cn/", Scode))  %>%  
        setXAxis(name = "", axisLabel = list(rotate = 30, textStyle=list(fontSize = 9))) %>% setYAxis(name = "(%)") %>%  
        setTooltip(show=T, trigger = 'axis', bgColor = "rgba(0,0,0,0)", textStyle = list(fontSize = 10, color = 'black')) %>%
        set_theme(width = 1000,height = 360, theme = 'macarons') %>% 
        setToolbox(show = T,controls = c("dataZoom", 'restore'), pos = 3) %>%
        set_legend(selected = c('Vib/%','Tra/%')) %>% 
        setDataZoom(fill=rgba(c(col2rgb('lightgreen'), 0.2)), handle=rgba(c(col2rgb('darkgreen'), 0.5)), range = c(50,100))
      # add trade markpoints 
      tradeRe = readRDS('e:/tess/tradeRe.RDS')
      if (Scode %in% names(tradeRe)) {
        Sto.dat = tradeRe[[Scode]]; Sto.dat = Sto.dat[order(Sto.dat$date, decreasing = F),]
        # add buy mark
        buyDat = Sto.dat[,c('date','buyN')]; buyDat= buyDat[which(buyDat$buyN != 0),]; 
        if (nrow(buyDat) > 0) {
          names(buyDat) = c('xAxis','value'); buyDat$series = 'Tra/%'; buyDat$name = 'buyN'
          buyDat$yAxis = Qplot.dat[which(Qplot.dat$compTime %in% buyDat$xAxis),5] * 1.05
        }
        # add sell mark
        sellDat = Sto.dat[,c('date','sellN')]; sellDat= sellDat[which(sellDat$sellN != 0),]; 
        if (nrow(sellDat) > 0) {
          names(sellDat) = c('xAxis','value'); sellDat$series = 'Vib/%'; sellDat$name = 'sellN'
          sellDat$yAxis = Qplot.dat[which(Qplot.dat$compTime %in% sellDat$xAxis),4] * 1.05
        }
        bs.dat = rbind.data.frame(buyDat, sellDat)
        if (nrow(bs.dat) > 0) {
          Qplot = Qplot %>% addMP(series = c('Tra/%', 'Vib/%'), data = bs.dat, symbolSize = 5)
        }
      }
      print("Note. PBR: price booking ratio(favor 1-5); PER: price earning ratio(favor 10-30); VR: Vibrate ratio; TR: Trade ratio.")
    }
    return(Qplot)
  } else print(paste0(Scode,' is not in subdata of ',type))
}
# trade report plot
tradePlot <- function(Scode) {
  tradeRe = readRDS('e:/tess/tradeRe.RDS')
  if (Scode %in% names(tradeRe)) {
    Sto.dat = tradeRe[[Scode]]; Sto.dat = Sto.dat[,1:11]
    Sto.dat[,c('buyN','holdN')] = Sto.dat[,c('buyN','holdN')] / (100)
    Sto.dat[,c('sellN')] = Sto.dat[,c('sellN')] / (-100)
    Sto.dat[,c('value','profit')] = Sto.dat[,c('value','profit')] / (1000)
    Sto.dat = data.table::melt(Sto.dat,id ='date')
    Sto.dat = Sto.dat[order(Sto.dat$date, decreasing = F),]
    plot = echartr(Sto.dat, as.character(date), value, variable, type='area', subtype = 'smooth') %>%
      setTitle(subtitle = paste0("Trading Reports of ", Scode), pos = 12, 
               sublink = paste0("http://stockpage.10jqka.com.cn/", Scode)) %>%  
      setXAxis(name = "", axisLabel = list(rotate = 30, textStyle=list(fontSize = 9))) %>% 
      setTooltip(show=T, trigger = 'axis', bgColor = "rgba(0,0,0,0)", textStyle = list(fontSize=9, color = 'black')) %>%
      setDataZoom(fill=rgba(c(col2rgb('lightgreen'), 0.2)), handle=rgba(c(col2rgb('darkgreen'), 0.5))) %>% 
      set_theme(width = 1000,height = 360, theme = 'macarons') %>% 
      setToolbox(show = T,controls = c("dataZoom", 'restore'), pos = 3) %>% 
      set_legend(selected = c('buyN','sellN','holdN'))
    print("variables 'buyN','holdN' divide by 100; ,'sellN' divide by -100; 'value','profit' divide by 1000.")
    return(plot)
  } else {cat(paste0('\nNo trade history of ', Scode,'\n'))}
}
# analyzing hsit info since clear
Anahis <- function(type = c('hold', 'hist'), Maxdays = 60) {
  # get analyze scodes
  if (type == 'hold') {
    Hsto.info = readRDS('e:/tess/Hsto.info.RDS')
    Scodes = Hsto.info$Code 
  } else if (type == 'hist') {
    tradeRe = readRDS('e:/tess/tradeRe.RDS'); histSto = names(tradeRe)
    spycode = readRDS('e:/tess/Hsto.info.RDS')$Code 
    Scodes = histSto[which(!histSto %in% spycode)]
  }
  #
  if (length(Scodes) > 0) {
    sto.dat = NULL; K.dat = NULL
    for (sto in Scodes) {
      dataK = readRDS('e:/tess/SpySto.RDS')[['sting']][[sto]][['dailyK']]
      if (type == 'hist') {
        # get start trade info
        clear.date = tradeRe[[sto]]$date[1]
        clear.price = tradeRe[[sto]]$price[1]
        clear.profit = tradeRe[[sto]]$profit[1]
        # get end info
        end.date = dataK$Date[1]
        end.price = dataK$CLOSE[1]
        # calculate new vars
        diffDays = which(dataK$Date == clear.date)
        start.hday = tradeRe[[sto]]$hday[1]
        diffHoldDays = start.hday + diffDays - 1
        start.date = dataK$Date[diffHoldDays]
        start.price = dataK$CLOSE[diffHoldDays]
        if (diffDays > Maxdays) {
          from = diffDays - Maxdays
          diffHighP = max(dataK$HIGH[from:diffDays]); dHP.pos = which.max(dataK$HIGH[from:diffDays]) + from
          diffLowP = min(dataK$LOW[from:diffDays]); dLP.pos = which.min(dataK$LOW[from:diffDays]) + from
        } else {
          diffHighP = max(dataK$HIGH[1:diffDays]); dHP.pos = which.max(dataK$HIGH[1:diffDays])
          diffLowP = min(dataK$LOW[1:diffDays]); dLP.pos = which.min(dataK$LOW[1:diffDays]) 
        }
        holdHighP = max(dataK$HIGH[diffDays:diffHoldDays]); holdLowP = min(dataK$LOW[diffDays:diffHoldDays]); 
        hHP.pos = which.max(dataK$HIGH[diffDays:diffHoldDays]) + diffDays - 1
        hLP.pos = which.min(dataK$LOW[diffDays:diffHoldDays]) + diffDays - 1
        dSymbol = ifelse(dHP.pos < dLP.pos, 'V', 'A'); hSymbol = ifelse(hHP.pos < hLP.pos, 'V', 'A')
        UpPer = round((diffHighP - clear.price) / clear.price * 100, 2)
        DownPer = round((diffLowP - clear.price) / clear.price * 100, 2)
        hUpPer = round((holdHighP - start.price) / start.price * 100, 2)
        hDownPer = round((holdLowP - start.price) / start.price * 100, 2)
        #
        sto.dat.i = data.frame(Scode = sto, Hdays = start.hday, diffDays = diffDays, Profit = clear.profit, 
                               StartPri = start.price, ClsPri = clear.price, EndPri = end.price, 
                               PerHigh = UpPer, PerLow = DownPer, hPerHigh = hUpPer, hPerLow = hDownPer, 
                               HP.pos = diffDays - dHP.pos + 1, LP.pos = diffDays - dLP.pos + 1, 
                               hHP.pos = diffHoldDays - hHP.pos + 1, hLP.pos = diffHoldDays - hLP.pos + 1,
                               Symbol = dSymbol, minView = diffHoldDays)
        sto.dat = rbind.data.frame(sto.dat, sto.dat.i)
        # get K.dat marklines
        Hvalue1 = clear.price; Second.pos = max(dLP.pos, dHP.pos); Third.pos = min(dLP.pos, dHP.pos)
        Hvalue2 = ifelse(dSymbol == 'V', dataK$LOW[Second.pos], dataK$HIGH[Second.pos])
        Hvalue2.pos = dataK$Date[Second.pos]
        Hvalue3 = ifelse(dSymbol == 'V', dataK$HIGH[Third.pos], dataK$LOW[Third.pos])
        Hvalue3.pos = dataK$Date[Third.pos]
        value1 = diffDays - Second.pos + 1
        value2 = ifelse(diffDays == Second.pos, diffDays - Third.pos, diffDays - Third.pos + 1)
        #
        Hvalue0 = start.price; Forth.pos = max(hLP.pos, hHP.pos); Fifth.pos = min(hLP.pos, hHP.pos)
        Hvalue4 = ifelse(hSymbol == 'V', dataK$LOW[Forth.pos], dataK$HIGH[Forth.pos])
        Hvalue4.pos = dataK$Date[Forth.pos]
        Hvalue5 = ifelse(hSymbol == 'V', dataK$HIGH[Fifth.pos], dataK$LOW[Fifth.pos])
        Hvalue5.pos = dataK$Date[Fifth.pos]
        value3 = diffHoldDays - Forth.pos + 1
        value4 = ifelse(diffHoldDays == Forth.pos, diffHoldDays - Fifth.pos, diffHoldDays - Fifth.pos + 1)
        line.1 <- data.frame(name1 = Hvalue1, xAxis1 = clear.date, yAxis1 = Hvalue1,
                             name2 = Hvalue2, xAxis2 = Hvalue2.pos, yAxis2 = Hvalue2, value = value1)
        line.2 <- data.frame(name1 = Hvalue2, xAxis1 = Hvalue2.pos, yAxis1 = Hvalue2,
                             name2 = Hvalue3, xAxis2 = Hvalue3.pos, yAxis2 = Hvalue3, value = value2)
        line.3 <- data.frame(name1 = Hvalue0, xAxis1 = start.date, yAxis1 = Hvalue0,
                             name2 = Hvalue4, xAxis2 = Hvalue4.pos, yAxis2 = Hvalue4, value = value3)
        line.4 <- data.frame(name1 = Hvalue4, xAxis1 = Hvalue4.pos, yAxis1 = Hvalue4,
                             name2 = Hvalue5, xAxis2 = Hvalue5.pos, yAxis2 = Hvalue5, value = value4)
        K.dat.i = rbind.data.frame(line.1, line.2, line.3, line.4)
        K.dat[[sto]] = K.dat.i
      } else if (type == 'hold') {
        # get start trade info
        start.hday = as.numeric(Hsto.info$Hdays[which(Hsto.info$Code == sto)])
        start.profit = as.numeric(Hsto.info$Profit[which(Hsto.info$Code == sto)])
        start.date = dataK$Date[start.hday]
        start.price = dataK$CLOSE[start.hday]
        # get end info
        end.date = dataK$Date[1]
        end.price = dataK$CLOSE[1]
        # calculate new vars
        diffDays = start.hday
        diffHighP = max(dataK$HIGH[1:diffDays]); dHP.pos = which.max(dataK$HIGH[1:diffDays])
        diffLowP = min(dataK$LOW[1:diffDays]); dLP.pos = which.min(dataK$LOW[1:diffDays]) 
        Symbol = ifelse(dHP.pos < dLP.pos, 'V', 'A')
        UpPer = round((diffHighP - start.price) / start.price * 100, 2)
        DownPer = round((diffLowP - start.price) / start.price * 100, 2)
        #
        sto.dat.i = data.frame(Scode = sto, Hdays = start.hday, Profit = start.profit, 
                               StartPri = start.price, EndPri = end.price, PerHigh = UpPer, PerLow = DownPer, 
                               HP.pos = diffDays - dHP.pos + 1, LP.pos = diffDays - dLP.pos + 1, 
                               Symbol = Symbol, minView = diffDays)
        sto.dat = rbind.data.frame(sto.dat, sto.dat.i)
        # get K.dat marklines
        Hvalue1 = start.price; Second.pos = max(dLP.pos, dHP.pos); Third.pos = min(dLP.pos, dHP.pos)
        Hvalue2 = ifelse(Symbol == 'V', dataK$LOW[Second.pos], dataK$HIGH[Second.pos])
        Hvalue2.pos = dataK$Date[Second.pos]
        Hvalue3 = ifelse(Symbol == 'V', dataK$HIGH[Third.pos], dataK$LOW[Third.pos])
        Hvalue3.pos = dataK$Date[Third.pos]
        value1 = diffDays - Second.pos + 1
        value2 = ifelse(diffDays == Second.pos, diffDays - Third.pos, diffDays - Third.pos + 1)
        line.1 <- data.frame(name1 = Hvalue1, xAxis1 = start.date, yAxis1 = Hvalue1,
                             name2 = Hvalue2, xAxis2 = Hvalue2.pos, yAxis2 = Hvalue2,value = value1)
        line.2 <- data.frame(name1 = Hvalue2, xAxis1 = Hvalue2.pos, yAxis1 = Hvalue2,
                             name2 = Hvalue3, xAxis2 = Hvalue3.pos, yAxis2 = Hvalue3,value = value2)
        K.dat.i = rbind.data.frame(line.1, line.2)
        K.dat[[sto]] = K.dat.i
      }
    }
    return(list(sto.dat = sto.dat, K.dat = K.dat))
  } else print("Please provide correct stock numbers.")
}
```

## Summary of holding stocks: 

```{r, echo=FALSE, warning=FALSE, fig.align='center'}
Hsto.info = readRDS('e:/tess/Hsto.info.RDS')
Hsto.dat = data.table::melt(Hsto.info, id.vars = c('Name', 'Code'))
rpivotTable::rpivotTable(Hsto.dat, rows = c('Name', 'Code'), cols = 'variable', 
                         aggregatorName = 'Sum', vals = 'value', rendererName = 'Col Heatmap', height = 900,
                         exclusions = list(variable = list('Var_1', 'FreezeN')))
```

## Analyzing history of holden stocks: 

```{r, echo=FALSE, warning=FALSE, fig.align='center'}
Anahis.res = Anahis(type = 'hold',Maxdays = 60)
Sto.dat = data.table::melt(Anahis.res[['sto.dat']], id.vars = c('Scode'))
rpivotTable::rpivotTable(Sto.dat, rows = 'Scode', cols = 'variable', aggregatorName = 'Sum', 
                               vals = 'value', rendererName = 'Col Heatmap', height = 900,
                               exclusions = list(variable = list('Symbol', 'minView')))
```

### Quick go to special Stock:
#### [300001](#300001); [603859](#603859); [300455](#300455); [603660](#603660); [300302](#300302); [300513](#300513)

<a name = '300001'></a>

## [Stock trading footsteps of 300001](http://stockpage.10jqka.com.cn/300001)   [[_Top_]](#)

```{r, echo=FALSE, warning=FALSE, fig.align='center'}
bandTest = bandSword('300001', bandFrom = 30, days = 10, ratio = 0.8)
ProRes = bandProfit('300001', bandRes = bandTest, Proless = 300)
if (length(ProRes[['BS.datT']]) > 1) {
                      rpivotTable::rpivotTable(ProRes[['BS.datT']], 
                      rows = 'tags', cols = c('bandDate','BS.Date','FinalHold'),
                      aggregatorName = 'Integer Sum', vals = 'profit', subtotals = T,
                      inclusions = list(bandDate = unique(ProRes[['BS.datT']]$bandDate)[1:6]),  
                      rendererName = 'Table With Subtotal Bar Chart', 
                      rendererOptions = list(collapseRowsAt = 0, collapseColsAt = 0))}
raw.sto <- read_html(paste0('http://stockpage.10jqka.com.cn/','300001'))
html_node(raw.sto,'strong') %>% html_text() %>% cat()
html_nodes(raw.sto, 'div.analyze-txt-cont') %>% html_text() %>% 
                    gsub('[\n\t]','',.) %>% print()
cat('K-plot with bandMark and trade lins of stock 300001')
SpyKplot('300001', bandRes = bandTest, viewNum = 60)
cat('K-line hostory plot of holden stock.')
Anahis.sto = Anahis.res[['K.dat']][['300001']]
viewNum = Anahis.res[['sto.dat']]$minView[which(Anahis.res[['sto.dat']]$Scode == '300001')] + 5
SpyKplot('300001', bandRes = Anahis.sto[c(1,3), c('xAxis1', 'value', 'name1', 'yAxis1')],
                             Protest = Anahis.sto, viewNum = viewNum, Randtheme = T)
StoQplot('300001', plot = c('StoIO'), viewNum = 60)
StoQplot('300001', plot = c('StoVP'), viewNum = 60)
tradePlot('300001')
```

<a name = '603859'></a>

## [Stock trading footsteps of 603859](http://stockpage.10jqka.com.cn/603859)   [[_Top_]](#)

```{r, echo=FALSE, warning=FALSE, fig.align='center'}
bandTest = bandSword('603859', bandFrom = 30, days = 10, ratio = 0.8)
ProRes = bandProfit('603859', bandRes = bandTest, Proless = 300)
if (length(ProRes[['BS.datT']]) > 1) {
                      rpivotTable::rpivotTable(ProRes[['BS.datT']], 
                      rows = 'tags', cols = c('bandDate','BS.Date','FinalHold'),
                      aggregatorName = 'Integer Sum', vals = 'profit', subtotals = T,
                      inclusions = list(bandDate = unique(ProRes[['BS.datT']]$bandDate)[1:6]),  
                      rendererName = 'Table With Subtotal Bar Chart', 
                      rendererOptions = list(collapseRowsAt = 0, collapseColsAt = 0))}
raw.sto <- read_html(paste0('http://stockpage.10jqka.com.cn/','603859'))
html_node(raw.sto,'strong') %>% html_text() %>% cat()
html_nodes(raw.sto, 'div.analyze-txt-cont') %>% html_text() %>% 
                    gsub('[\n\t]','',.) %>% print()
cat('K-plot with bandMark and trade lins of stock 603859')
SpyKplot('603859', bandRes = bandTest, viewNum = 60)
cat('K-line hostory plot of holden stock.')
Anahis.sto = Anahis.res[['K.dat']][['603859']]
viewNum = Anahis.res[['sto.dat']]$minView[which(Anahis.res[['sto.dat']]$Scode == '603859')] + 5
SpyKplot('603859', bandRes = Anahis.sto[c(1,3), c('xAxis1', 'value', 'name1', 'yAxis1')],
                             Protest = Anahis.sto, viewNum = viewNum, Randtheme = T)
StoQplot('603859', plot = c('StoIO'), viewNum = 60)
StoQplot('603859', plot = c('StoVP'), viewNum = 60)
tradePlot('603859')
```

<a name = '300455'></a>

## [Stock trading footsteps of 300455](http://stockpage.10jqka.com.cn/300455)   [[_Top_]](#)

```{r, echo=FALSE, warning=FALSE, fig.align='center'}
bandTest = bandSword('300455', bandFrom = 30, days = 10, ratio = 0.8)
ProRes = bandProfit('300455', bandRes = bandTest, Proless = 300)
if (length(ProRes[['BS.datT']]) > 1) {
                      rpivotTable::rpivotTable(ProRes[['BS.datT']], 
                      rows = 'tags', cols = c('bandDate','BS.Date','FinalHold'),
                      aggregatorName = 'Integer Sum', vals = 'profit', subtotals = T,
                      inclusions = list(bandDate = unique(ProRes[['BS.datT']]$bandDate)[1:6]),  
                      rendererName = 'Table With Subtotal Bar Chart', 
                      rendererOptions = list(collapseRowsAt = 0, collapseColsAt = 0))}
raw.sto <- read_html(paste0('http://stockpage.10jqka.com.cn/','300455'))
html_node(raw.sto,'strong') %>% html_text() %>% cat()
html_nodes(raw.sto, 'div.analyze-txt-cont') %>% html_text() %>% 
                    gsub('[\n\t]','',.) %>% print()
cat('K-plot with bandMark and trade lins of stock 300455')
SpyKplot('300455', bandRes = bandTest, viewNum = 60)
cat('K-line hostory plot of holden stock.')
Anahis.sto = Anahis.res[['K.dat']][['300455']]
viewNum = Anahis.res[['sto.dat']]$minView[which(Anahis.res[['sto.dat']]$Scode == '300455')] + 5
SpyKplot('300455', bandRes = Anahis.sto[c(1,3), c('xAxis1', 'value', 'name1', 'yAxis1')],
                             Protest = Anahis.sto, viewNum = viewNum, Randtheme = T)
StoQplot('300455', plot = c('StoIO'), viewNum = 60)
StoQplot('300455', plot = c('StoVP'), viewNum = 60)
tradePlot('300455')
```

<a name = '603660'></a>

## [Stock trading footsteps of 603660](http://stockpage.10jqka.com.cn/603660)   [[_Top_]](#)

```{r, echo=FALSE, warning=FALSE, fig.align='center'}
bandTest = bandSword('603660', bandFrom = 30, days = 10, ratio = 0.8)
ProRes = bandProfit('603660', bandRes = bandTest, Proless = 300)
if (length(ProRes[['BS.datT']]) > 1) {
                      rpivotTable::rpivotTable(ProRes[['BS.datT']], 
                      rows = 'tags', cols = c('bandDate','BS.Date','FinalHold'),
                      aggregatorName = 'Integer Sum', vals = 'profit', subtotals = T,
                      inclusions = list(bandDate = unique(ProRes[['BS.datT']]$bandDate)[1:6]),  
                      rendererName = 'Table With Subtotal Bar Chart', 
                      rendererOptions = list(collapseRowsAt = 0, collapseColsAt = 0))}
raw.sto <- read_html(paste0('http://stockpage.10jqka.com.cn/','603660'))
html_node(raw.sto,'strong') %>% html_text() %>% cat()
html_nodes(raw.sto, 'div.analyze-txt-cont') %>% html_text() %>% 
                    gsub('[\n\t]','',.) %>% print()
cat('K-plot with bandMark and trade lins of stock 603660')
SpyKplot('603660', bandRes = bandTest, viewNum = 60)
cat('K-line hostory plot of holden stock.')
Anahis.sto = Anahis.res[['K.dat']][['603660']]
viewNum = Anahis.res[['sto.dat']]$minView[which(Anahis.res[['sto.dat']]$Scode == '603660')] + 5
SpyKplot('603660', bandRes = Anahis.sto[c(1,3), c('xAxis1', 'value', 'name1', 'yAxis1')],
                             Protest = Anahis.sto, viewNum = viewNum, Randtheme = T)
StoQplot('603660', plot = c('StoIO'), viewNum = 60)
StoQplot('603660', plot = c('StoVP'), viewNum = 60)
tradePlot('603660')
```

<a name = '300302'></a>

## [Stock trading footsteps of 300302](http://stockpage.10jqka.com.cn/300302)   [[_Top_]](#)

```{r, echo=FALSE, warning=FALSE, fig.align='center'}
bandTest = bandSword('300302', bandFrom = 30, days = 10, ratio = 0.8)
ProRes = bandProfit('300302', bandRes = bandTest, Proless = 300)
if (length(ProRes[['BS.datT']]) > 1) {
                      rpivotTable::rpivotTable(ProRes[['BS.datT']], 
                      rows = 'tags', cols = c('bandDate','BS.Date','FinalHold'),
                      aggregatorName = 'Integer Sum', vals = 'profit', subtotals = T,
                      inclusions = list(bandDate = unique(ProRes[['BS.datT']]$bandDate)[1:6]),  
                      rendererName = 'Table With Subtotal Bar Chart', 
                      rendererOptions = list(collapseRowsAt = 0, collapseColsAt = 0))}
raw.sto <- read_html(paste0('http://stockpage.10jqka.com.cn/','300302'))
html_node(raw.sto,'strong') %>% html_text() %>% cat()
html_nodes(raw.sto, 'div.analyze-txt-cont') %>% html_text() %>% 
                    gsub('[\n\t]','',.) %>% print()
cat('K-plot with bandMark and trade lins of stock 300302')
SpyKplot('300302', bandRes = bandTest, viewNum = 60)
cat('K-line hostory plot of holden stock.')
Anahis.sto = Anahis.res[['K.dat']][['300302']]
viewNum = Anahis.res[['sto.dat']]$minView[which(Anahis.res[['sto.dat']]$Scode == '300302')] + 5
SpyKplot('300302', bandRes = Anahis.sto[c(1,3), c('xAxis1', 'value', 'name1', 'yAxis1')],
                             Protest = Anahis.sto, viewNum = viewNum, Randtheme = T)
StoQplot('300302', plot = c('StoIO'), viewNum = 60)
StoQplot('300302', plot = c('StoVP'), viewNum = 60)
tradePlot('300302')
```

<a name = '300513'></a>

## [Stock trading footsteps of 300513](http://stockpage.10jqka.com.cn/300513)   [[_Top_]](#)

```{r, echo=FALSE, warning=FALSE, fig.align='center'}
bandTest = bandSword('300513', bandFrom = 30, days = 10, ratio = 0.8)
ProRes = bandProfit('300513', bandRes = bandTest, Proless = 300)
if (length(ProRes[['BS.datT']]) > 1) {
                      rpivotTable::rpivotTable(ProRes[['BS.datT']], 
                      rows = 'tags', cols = c('bandDate','BS.Date','FinalHold'),
                      aggregatorName = 'Integer Sum', vals = 'profit', subtotals = T,
                      inclusions = list(bandDate = unique(ProRes[['BS.datT']]$bandDate)[1:6]),  
                      rendererName = 'Table With Subtotal Bar Chart', 
                      rendererOptions = list(collapseRowsAt = 0, collapseColsAt = 0))}
raw.sto <- read_html(paste0('http://stockpage.10jqka.com.cn/','300513'))
html_node(raw.sto,'strong') %>% html_text() %>% cat()
html_nodes(raw.sto, 'div.analyze-txt-cont') %>% html_text() %>% 
                    gsub('[\n\t]','',.) %>% print()
cat('K-plot with bandMark and trade lins of stock 300513')
SpyKplot('300513', bandRes = bandTest, viewNum = 60)
cat('K-line hostory plot of holden stock.')
Anahis.sto = Anahis.res[['K.dat']][['300513']]
viewNum = Anahis.res[['sto.dat']]$minView[which(Anahis.res[['sto.dat']]$Scode == '300513')] + 5
SpyKplot('300513', bandRes = Anahis.sto[c(1,3), c('xAxis1', 'value', 'name1', 'yAxis1')],
                             Protest = Anahis.sto, viewNum = viewNum, Randtheme = T)
StoQplot('300513', plot = c('StoIO'), viewNum = 60)
StoQplot('300513', plot = c('StoVP'), viewNum = 60)
tradePlot('300513')
```

Note: reports updated on 2020-06-29